services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    depends_on:
      - timescaledb
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data: